### ISSUE TITLE
Use this to programmatically vibrate MiBand 3?

### ISSUE THREAD

**Issue by hawkwood** [ictinnovaties-zorg/openwindesheart#1]
I came across this repo as I'm trying to make a proof-of-concept project using a MiBand 3, which requires me to be able to programmatically vibrate the MiBand, preferably with some level of variability.  I glanced through the code and did not seem to find if this is possible. Can you tell me if it is?

**Comment by ramonB1996** [comment]
Hi hawkwood,

To vibrate the mi band 3 there seems to be a call to a function that actually does something else too, like authenticating or receiving messages, etc.. I could not find any characteristics that allow just 'vibrating' without anything happening.

Our codebase only vibrates on authentication, which would not be good enough for your use-case I guess.
Our source of the available characteristics was gadgetbridge: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami

You might find some interesting things, so take a look if you want. That project is written in Java.
It does look like they have something with variable vibrations in their sample app, so take a look at their wiki too: 
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Configuration#mi-band--amazfit-specific-settings

I am sorry I can not help you anything further with this. Characteristics of the Xiaomi bands are not documented anywhere, because they are supposed to be 'closed-source'. That makes it harder to find the characteristics you need.

Kind regards,
Ramon
